name: firebase_aoy
description: "A new Flutter project."
publish_to: 'none'

# Defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  email_validator: ^3.0.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  flutter_bloc: ^8.1.0
  bloc: ^8.1.0
  equatable: ^2.0.5
  lottie: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo6-.png
