// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
              'Please re-run the FlutterFire CLI to configure for unsupported platforms.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaSljojpDHIM61XXYjBrAGf8H-1LqwPZM',
    appId: '1:88663121547:web:b48dce88a5aa9b63147e8e',
    messagingSenderId: '88663121547',
    projectId: 'device-streaming-b55286bc',
    authDomain: 'device-streaming-b55286bc.firebaseapp.com',
    storageBucket: 'device-streaming-b55286bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj6844Waaguk4bPtEKFNK0rghtIWcJ43k',
    appId: '1:88663121547:android:5dc85b731965b695147e8e',
    messagingSenderId: '88663121547',
    projectId: 'device-streaming-b55286bc',
    storageBucket: 'device-streaming-b55286bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAApMOQh_6CqfFtoSKrArTgJjhZhiZMsKA',
    appId: '1:88663121547:ios:ae1524f39d12218d147e8e',
    messagingSenderId: '88663121547',
    projectId: 'device-streaming-b55286bc',
    storageBucket: 'device-streaming-b55286bc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAoy',
  );

}